/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This parameter specifies the target object (individual UE) for the QMC in case of signalling based QMC. It shall be able to carry an IMSI or a SUPI. 
type QoeTarget struct {
	Supi string `json:"supi,omitempty"`
	Imsi string `json:"imsi,omitempty"`
}
