/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AdditionalSnssaiData struct {
	RequiredAuthnAuthz bool `json:"requiredAuthnAuthz,omitempty"`
	SubscribedUeSliceMbr *SliceMbrRm `json:"subscribedUeSliceMbr,omitempty"`
	SubscribedNsSrgList []string `json:"subscribedNsSrgList,omitempty"`
	NsacMode *NsacAdmissionMode `json:"nsacMode,omitempty"`
	ValidTimePeriod *ValidTimePeriod `json:"validTimePeriod,omitempty"`
	DeregInactTimer int32 `json:"deregInactTimer,omitempty"`
	OnDemand bool `json:"onDemand,omitempty"`
}
