/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AccessAndMobilitySubscriptionData struct {
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	Gpsis []string `json:"gpsis,omitempty"`
	HssGroupId string `json:"hssGroupId,omitempty"`
	InternalGroupIds []string `json:"internalGroupIds,omitempty"`
	// A map(list of key-value pairs) where GroupId serves as key of SharedDataId
	SharedVnGroupDataIds map[string]string `json:"sharedVnGroupDataIds,omitempty"`
	SubscribedUeAmbr *AmbrRm `json:"subscribedUeAmbr,omitempty"`
	Nssai *Nssai `json:"nssai,omitempty"`
	RatRestrictions []RatType `json:"ratRestrictions,omitempty"`
	ForbiddenAreas []Area `json:"forbiddenAreas,omitempty"`
	ServiceAreaRestriction *ServiceAreaRestriction `json:"serviceAreaRestriction,omitempty"`
	CoreNetworkTypeRestrictions []CoreNetworkType `json:"coreNetworkTypeRestrictions,omitempty"`
	AccessTypeRestrictions []AccessType `json:"accessTypeRestrictions,omitempty"`
	RfspIndex int32 `json:"rfspIndex,omitempty"`
	SubsRegTimer int32 `json:"subsRegTimer,omitempty"`
	UeUsageType int32 `json:"ueUsageType,omitempty"`
	MpsPriority bool `json:"mpsPriority,omitempty"`
	McsPriority bool `json:"mcsPriority,omitempty"`
	ActiveTime int32 `json:"activeTime,omitempty"`
	SorInfo *SorInfo `json:"sorInfo,omitempty"`
	SorInfoExpectInd bool `json:"sorInfoExpectInd,omitempty"`
	SorafRetrieval bool `json:"sorafRetrieval,omitempty"`
	SorUpdateIndicatorList []SorUpdateIndicator `json:"sorUpdateIndicatorList,omitempty"`
	UpuInfo *UpuInfo `json:"upuInfo,omitempty"`
	RoutingIndicator string `json:"routingIndicator,omitempty"`
	MicoAllowed bool `json:"micoAllowed,omitempty"`
	SharedAmDataIds []string `json:"sharedAmDataIds,omitempty"`
	OdbPacketServices *OdbPacketServices `json:"odbPacketServices,omitempty"`
	SubscribedDnnList []AnyOfAccessAndMobilitySubscriptionDataSubscribedDnnListItems `json:"subscribedDnnList,omitempty"`
	ServiceGapTime int32 `json:"serviceGapTime,omitempty"`
	MdtUserConsent *MdtUserConsent `json:"mdtUserConsent,omitempty"`
	// A map (list of key-value pairs where PlmnId serves as key) of MdtUserConsent
	AdjacentPlmnMdtUserConsents map[string]MdtUserConsent `json:"adjacentPlmnMdtUserConsents,omitempty"`
	MdtConfiguration *MdtConfiguration `json:"mdtConfiguration,omitempty"`
	TraceData *TraceData `json:"traceData,omitempty"`
	SharedTraceDataId string `json:"sharedTraceDataId,omitempty"`
	CagData *CagData `json:"cagData,omitempty"`
	StnSr string `json:"stnSr,omitempty"`
	CMsisdn string `json:"cMsisdn,omitempty"`
	NbIoTUePriority int32 `json:"nbIoTUePriority,omitempty"`
	NssaiInclusionAllowed bool `json:"nssaiInclusionAllowed,omitempty"`
	RgWirelineCharacteristics *Bytes `json:"rgWirelineCharacteristics,omitempty"`
	Aun3DeviceConnectivityAllowed bool `json:"aun3DeviceConnectivityAllowed,omitempty"`
	EcRestrictionDataWb *EcRestrictionDataWb `json:"ecRestrictionDataWb,omitempty"`
	EcRestrictionDataNb bool `json:"ecRestrictionDataNb,omitempty"`
	ExpectedUeBehaviourList *ExpectedUeBehaviourData `json:"expectedUeBehaviourList,omitempty"`
	// A map(list of key-value pairs) where a valid JSON pointer serves as key
	ExpectedUeBehaviourData map[string]ExpectedUeBehaviourData `json:"expectedUeBehaviourData,omitempty"`
	PrimaryRatRestrictions []RatType `json:"primaryRatRestrictions,omitempty"`
	SecondaryRatRestrictions []RatType `json:"secondaryRatRestrictions,omitempty"`
	EdrxParametersList []EdrxParameters `json:"edrxParametersList,omitempty"`
	PtwParametersList []PtwParameters `json:"ptwParametersList,omitempty"`
	IabOperationAllowed bool `json:"iabOperationAllowed,omitempty"`
	// A map (list of key-value pairs where PlmnId serves as key) of PlmnRestriction
	AdjacentPlmnRestrictions map[string]PlmnRestriction `json:"adjacentPlmnRestrictions,omitempty"`
	WirelineForbiddenAreas []WirelineArea `json:"wirelineForbiddenAreas,omitempty"`
	WirelineServiceAreaRestriction *WirelineServiceAreaRestriction `json:"wirelineServiceAreaRestriction,omitempty"`
	PcfSelectionAssistanceInfos []PcfSelectionAssistanceInfo `json:"pcfSelectionAssistanceInfos,omitempty"`
	AerialUeSubInfo *AerialUeSubscriptionInfo `json:"aerialUeSubInfo,omitempty"`
	RoamingRestrictions *RoamingRestrictions `json:"roamingRestrictions,omitempty"`
	RemoteProvInd bool `json:"remoteProvInd,omitempty"`
	Var3gppChargingCharacteristics string `json:"3gppChargingCharacteristics,omitempty"`
	TimeSyncData *TimeSyncData `json:"timeSyncData,omitempty"`
	SharedDataList []SharedData `json:"sharedDataList,omitempty"`
	QmcConfigInfo *QmcConfigInfo `json:"qmcConfigInfo,omitempty"`
	MbsrOperationAllowed *MbsrOperationAllowed `json:"mbsrOperationAllowed,omitempty"`
	NcrOperationAllowed bool `json:"ncrOperationAllowed,omitempty"`
	// A map(list of key-value pairs where singleNssai serves as key) of DnnLadnServiceAreas
	LadnServiceAreas map[string]DnnLadnServiceAreas `json:"ladnServiceAreas,omitempty"`
}
