/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved.
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// AccessType : Indicates whether the access is  via 3GPP or via non-3GPP.
type AccessType string

// List of AccessType
const (
	_3GPPACCESS__AccessType     AccessType = "3GPP_ACCESS"
	NON_3_GPP_ACCESS_AccessType AccessType = "NON_3GPP_ACCESS"
)
