/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PgwInfo struct {
	Dnn string `json:"dnn"`
	PgwFqdn string `json:"pgwFqdn"`
	PgwIpAddr *IpAddress `json:"pgwIpAddr,omitempty"`
	PlmnId *PlmnId `json:"plmnId,omitempty"`
	EpdgInd bool `json:"epdgInd,omitempty"`
	PcfId string `json:"pcfId,omitempty"`
	RegistrationTime *time.Time `json:"registrationTime,omitempty"`
	WildcardInd bool `json:"wildcardInd,omitempty"`
}
