/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SmfSelectionSubscriptionData struct {
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	// A map(list of key-value pairs) where singleNssai serves as key of SnssaiInfo
	SubscribedSnssaiInfos map[string]SnssaiInfo `json:"subscribedSnssaiInfos,omitempty"`
	SharedSnssaiInfosId string `json:"sharedSnssaiInfosId,omitempty"`
	HssGroupId string `json:"hssGroupId,omitempty"`
}
