/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Contains the PLMN identities where the Ranging/SL Positioning services are authorised to use and the authorised Ranging/SL Positioning services on this given PLMNs.
type RangingSlPosPlmn struct {
	RangingSlPosPlmn *PlmnId `json:"rangingSlPosPlmn"`
	RangingSlPosAllowed []RangingSlPosAllowed `json:"rangingSlPosAllowed,omitempty"`
}
