/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Ellipsoid Arc.
type EllipsoidArc struct {
	Point *GeographicalCoordinates `json:"point"`
	InnerRadius int32 `json:"innerRadius"`
	UncertaintyRadius float32 `json:"uncertaintyRadius"`
	OffsetAngle int32 `json:"offsetAngle"`
	IncludedAngle int32 `json:"includedAngle"`
	Confidence int32 `json:"confidence"`
	Shape *SupportedGadShapes `json:"shape"`
}
