/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SessionManagementSubscriptionData struct {
	SingleNssai *Snssai `json:"singleNssai"`
	// A map (list of key-value pairs where Dnn, or optionally the Wildcard DNN, serves as key) of DnnConfigurations
	DnnConfigurations map[string]DnnConfiguration `json:"dnnConfigurations,omitempty"`
	InternalGroupIds []string `json:"internalGroupIds,omitempty"`
	// A map(list of key-value pairs) where GroupId serves as key of SharedDataId
	SharedVnGroupDataIds map[string]string `json:"sharedVnGroupDataIds,omitempty"`
	SharedDnnConfigurationsId string `json:"sharedDnnConfigurationsId,omitempty"`
	OdbPacketServices *OdbPacketServices `json:"odbPacketServices,omitempty"`
	TraceData *TraceData `json:"traceData,omitempty"`
	SharedTraceDataId string `json:"sharedTraceDataId,omitempty"`
	// A map(list of key-value pairs) where Dnn serves as key of ExpectedUeBehaviourData
	ExpectedUeBehavioursList map[string]ExpectedUeBehaviourData `json:"expectedUeBehavioursList,omitempty"`
	// A map(list of key-value pairs) where DNN serves as key
	ExpectedUeBehaviourData map[string]map[string]ExpectedUeBehaviourData `json:"expectedUeBehaviourData,omitempty"`
	// A map(list of key-value pairs) where DNN serves as key
	AppSpecificExpectedUeBehaviourData map[string]map[string]AppSpecificExpectedUeBehaviourData `json:"appSpecificExpectedUeBehaviourData,omitempty"`
	// A map(list of key-value pairs) where Dnn serves as key of SuggestedPacketNumDl
	SuggestedPacketNumDlList map[string]SuggestedPacketNumDl `json:"suggestedPacketNumDlList,omitempty"`
	Var3gppChargingCharacteristics string `json:"3gppChargingCharacteristics,omitempty"`
	NsacMode *NsacAdmissionMode `json:"nsacMode,omitempty"`
	SessInactTimer int32 `json:"sessInactTimer,omitempty"`
	OnDemand bool `json:"onDemand,omitempty"`
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	AdditionalSharedDnnConfigurationsIds []string `json:"additionalSharedDnnConfigurationsIds,omitempty"`
}
