/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type DnnInfo struct {
	Dnn *AnyOfDnnInfoDnn `json:"dnn"`
	DefaultDnnIndicator bool `json:"defaultDnnIndicator,omitempty"`
	LboRoamingAllowed bool `json:"lboRoamingAllowed,omitempty"`
	IwkEpsInd bool `json:"iwkEpsInd,omitempty"`
	DnnBarred bool `json:"dnnBarred,omitempty"`
	InvokeNefInd bool `json:"invokeNefInd,omitempty"`
	SmfList []string `json:"smfList,omitempty"`
	SameSmfInd bool `json:"sameSmfInd,omitempty"`
	HrSboAllowed bool `json:"hrSboAllowed,omitempty"`
}
