/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type RangingSlPosQos struct {
	HAccuracy float32 `json:"hAccuracy,omitempty"`
	VAccuracy float32 `json:"vAccuracy,omitempty"`
	RelativeHAccuracy float32 `json:"relativeHAccuracy,omitempty"`
	RelativeVAccuracy float32 `json:"relativeVAccuracy,omitempty"`
	DistanceAccuracy float32 `json:"distanceAccuracy,omitempty"`
	DirectionAccuracy float32 `json:"directionAccuracy,omitempty"`
	VerticalRequested bool `json:"verticalRequested,omitempty"`
	ResponseTime *ResponseTime `json:"responseTime,omitempty"`
	LcsQosClass *LcsQosClass `json:"lcsQosClass,omitempty"`
}
