/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type AppSpecificExpectedUeBehaviourData struct {
	AppId string `json:"appId,omitempty"`
	TrafficFilters []FlowInfo `json:"trafficFilters,omitempty"`
	ExpectedInactivityTime int32 `json:"expectedInactivityTime,omitempty"`
	ValidityTime *time.Time `json:"validityTime,omitempty"`
	ConfidenceLevel string `json:"confidenceLevel,omitempty"`
	AccuracyLevel string `json:"accuracyLevel,omitempty"`
}
