/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VnGroupData struct {
	PduSessionTypes *PduSessionTypes `json:"pduSessionTypes,omitempty"`
	Dnn string `json:"dnn,omitempty"`
	SingleNssai *Snssai `json:"singleNssai,omitempty"`
	AppDescriptors []AppDescriptor `json:"appDescriptors,omitempty"`
	SecondaryAuth bool `json:"secondaryAuth,omitempty"`
	DnAaaIpAddressAllocation bool `json:"dnAaaIpAddressAllocation,omitempty"`
	DnAaaAddress *IpAddress `json:"dnAaaAddress,omitempty"`
	AdditionalDnAaaAddresses []IpAddress `json:"additionalDnAaaAddresses,omitempty"`
	DnAaaFqdn string `json:"dnAaaFqdn,omitempty"`
}
