/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Provides information about allowed or not allowed areas.
type ServiceAreaRestriction struct {
	RestrictionType *RestrictionType `json:"restrictionType,omitempty"`
	Areas []Area `json:"areas,omitempty"`
	MaxNumOfTAs int32 `json:"maxNumOfTAs,omitempty"`
	MaxNumOfTAsForNotAllowedAreas int32 `json:"maxNumOfTAsForNotAllowedAreas,omitempty"`
}
