/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// UE Context In Smf Data Subscription Filter.
type UeContextInSmfDataSubFilter struct {
	DnnList []string `json:"dnnList,omitempty"`
	SnssaiList []Snssai `json:"snssaiList,omitempty"`
	EmergencyInd bool `json:"emergencyInd,omitempty"`
}
