/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Contains the tracking area identity as described in 3GPP 23.003
type Tai struct {
	PlmnId *PlmnId `json:"plmnId"`
	Tac string `json:"tac"`
	Nid string `json:"nid,omitempty"`
}
