/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type Nssai struct {
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	DefaultSingleNssais []Snssai `json:"defaultSingleNssais"`
	SingleNssais []Snssai `json:"singleNssais,omitempty"`
	ProvisioningTime *time.Time `json:"provisioningTime,omitempty"`
	// A map(list of key-value pairs) where singleNssai serves as key of AdditionalSnssaiData
	AdditionalSnssaiData map[string]AdditionalSnssaiData `json:"additionalSnssaiData,omitempty"`
	SuppressNssrgInd bool `json:"suppressNssrgInd,omitempty"`
	// A map(list of key-value pairs where single Nssai serves as key) of the current validity time 
	NssaiValidityTimeInfo map[string]time.Time `json:"nssaiValidityTimeInfo,omitempty"`
}
