/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type SorInfo struct {
	SteeringContainer *SteeringContainer `json:"steeringContainer,omitempty"`
	AckInd bool `json:"ackInd"`
	SorMacIausf string `json:"sorMacIausf,omitempty"`
	Countersor string `json:"countersor,omitempty"`
	ProvisioningTime *time.Time `json:"provisioningTime"`
	SorTransparentContainer string `json:"sorTransparentContainer,omitempty"`
	SorCmci string `json:"sorCmci,omitempty"`
	SorSnpnSi string `json:"sorSnpnSi,omitempty"`
	SorSnpnSiLs string `json:"sorSnpnSiLs,omitempty"`
	StoreSorCmciInMe bool `json:"storeSorCmciInMe,omitempty"`
	UsimSupportOfSorCmci bool `json:"usimSupportOfSorCmci,omitempty"`
}
