/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Contains Clock Quality.
type ClockQuality struct {
	TraceabilityToGnss bool `json:"traceabilityToGnss,omitempty"`
	TraceabilityToUtc bool `json:"traceabilityToUtc,omitempty"`
	FrequencyStability int32 `json:"frequencyStability,omitempty"`
	ClockAccuracyIndex string `json:"clockAccuracyIndex,omitempty"`
	ClockAccuracyValue int32 `json:"clockAccuracyValue,omitempty"`
}
