/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type UpuInfo struct {
	UpuDataList []UpuData `json:"upuDataList,omitempty"`
	UpuRegInd bool `json:"upuRegInd,omitempty"`
	UpuAckInd bool `json:"upuAckInd,omitempty"`
	UpuMacIausf string `json:"upuMacIausf,omitempty"`
	CounterUpu string `json:"counterUpu,omitempty"`
	ProvisioningTime *time.Time `json:"provisioningTime"`
	UpuTransparentContainer string `json:"upuTransparentContainer,omitempty"`
}
