/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Provides the subsribed 5QI and the ARP, it may contain the priority level.
type SubscribedDefaultQos struct {
	Var5qi int32 `json:"5qi"`
	Arp *Arp `json:"arp"`
	PriorityLevel int32 `json:"priorityLevel,omitempty"`
}
