/*
 * Nudm_SDM
 *
 * Nudm Subscriber Data Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 2.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type CagData struct {
	// A map (list of key-value pairs where PlmnId serves as key) of CagInfo
	CagInfos map[string]CagInfo `json:"cagInfos"`
	// A map (list of key-value pairs where PlmnId serves as key) of CagInfo
	ConditionalCagInfos map[string]ConditionalCagInfo `json:"conditionalCagInfos,omitempty"`
	ProvisioningTime *time.Time `json:"provisioningTime,omitempty"`
}
