/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Error returned in the access token response message
type AccessTokenErr struct {
	Error_ string `json:"error"`
	ErrorDescription string `json:"error_description,omitempty"`
	ErrorUri string `json:"error_uri,omitempty"`
}
