/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Provides the reason for not finding NF matching the search criteria
type NoProfileMatchInfo struct {
	Reason *NoProfileMatchReason `json:"reason"`
	QueryParamCombinationList []QueryParamCombination `json:"queryParamCombinationList,omitempty"`
}
