/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This data type contains the information about serving AMF, optional VGMLC and access type related information used by (H)GMLC. 
type RegistrationLocationInfo struct {
	AmfInstanceId string `json:"amfInstanceId"`
	Guami *Guami `json:"guami,omitempty"`
	PlmnId *PlmnId `json:"plmnId,omitempty"`
	VgmlcAddress *VgmlcAddress `json:"vgmlcAddress,omitempty"`
	AccessTypeList []AccessType `json:"accessTypeList"`
}
