/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Represents the complete set of information relevant to the AMF when the UE has registered via non 3GPP access. 
type AmfNon3GppAccessRegistration struct {
	AmfInstanceId string `json:"amfInstanceId"`
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	PurgeFlag bool `json:"purgeFlag,omitempty"`
	Pei string `json:"pei,omitempty"`
	ImsVoPs *ImsVoPs `json:"imsVoPs"`
	DeregCallbackUri string `json:"deregCallbackUri"`
	AmfServiceNameDereg *ServiceName `json:"amfServiceNameDereg,omitempty"`
	PcscfRestorationCallbackUri string `json:"pcscfRestorationCallbackUri,omitempty"`
	AmfServiceNamePcscfRest *ServiceName `json:"amfServiceNamePcscfRest,omitempty"`
	Guami *Guami `json:"guami"`
	BackupAmfInfo []BackupAmfInfo `json:"backupAmfInfo,omitempty"`
	RatType *RatType `json:"ratType"`
	UrrpIndicator bool `json:"urrpIndicator,omitempty"`
	AmfEeSubscriptionId string `json:"amfEeSubscriptionId,omitempty"`
	RegistrationTime *time.Time `json:"registrationTime,omitempty"`
	VgmlcAddress *VgmlcAddress `json:"vgmlcAddress,omitempty"`
	ContextInfo *ContextInfo `json:"contextInfo,omitempty"`
	NoEeSubscriptionInd bool `json:"noEeSubscriptionInd,omitempty"`
	Supi string `json:"supi,omitempty"`
	ReRegistrationRequired bool `json:"reRegistrationRequired,omitempty"`
	AdminDeregSubWithdrawn bool `json:"adminDeregSubWithdrawn,omitempty"`
	DataRestorationCallbackUri string `json:"dataRestorationCallbackUri,omitempty"`
	ResetIds []string `json:"resetIds,omitempty"`
	DisasterRoamingInd bool `json:"disasterRoamingInd,omitempty"`
	SorSnpnSiSupported bool `json:"sorSnpnSiSupported,omitempty"`
	UdrRestartInd bool `json:"udrRestartInd,omitempty"`
	LastSynchronizationTime *time.Time `json:"lastSynchronizationTime,omitempty"`
}
