/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Addressing information of the SMS Router configured at the UDM
type SmsRouterInfo struct {
	NfInstanceId string `json:"nfInstanceId,omitempty"`
	DiameterAddress *NetworkNodeDiameterAddress `json:"diameterAddress,omitempty"`
	MapAddress string `json:"mapAddress,omitempty"`
	RouterIpv4 string `json:"routerIpv4,omitempty"`
	RouterIpv6 *Ipv6Addr `json:"routerIpv6,omitempty"`
	RouterFqdn string `json:"routerFqdn,omitempty"`
}
