/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// The complete set of information relevant to an NWDAF serving the UE
type NwdafRegistration struct {
	NwdafInstanceId string `json:"nwdafInstanceId"`
	AnalyticsIds []EventId `json:"analyticsIds"`
	NwdafSetId string `json:"nwdafSetId,omitempty"`
	RegistrationTime *time.Time `json:"registrationTime,omitempty"`
	ContextInfo *ContextInfo `json:"contextInfo,omitempty"`
	SupportedFeatures string `json:"supportedFeatures,omitempty"`
	ResetIds []string `json:"resetIds,omitempty"`
}
