/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// A range of SUPIs (subscriber identities), either based on a numeric range, or based on regular-expression matching 
type SupiRange struct {
	Start string `json:"start,omitempty"`
	End string `json:"end,omitempty"`
	Pattern string `json:"pattern,omitempty"`
}
