/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This datatype is supported by the POST HTTP method, and it includes the deregistration data. 
type DeregistrationData struct {
	DeregReason *DeregistrationReason `json:"deregReason"`
	AccessType *AccessType `json:"accessType,omitempty"`
	PduSessionId int32 `json:"pduSessionId,omitempty"`
	NewSmfInstanceId string `json:"newSmfInstanceId,omitempty"`
}
