/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Addressing information of available nodes for SMS delivery
type RoutingInfoSmResponse struct {
	Supi string `json:"supi,omitempty"`
	Smsf3Gpp *SmsfRegistration `json:"smsf3Gpp,omitempty"`
	SmsfNon3Gpp *SmsfRegistration `json:"smsfNon3Gpp,omitempty"`
	IpSmGw *IpSmGwInfo `json:"ipSmGw,omitempty"`
	SmsRouter *SmsRouterInfo `json:"smsRouter,omitempty"`
}
