/*
 * Nudm_UECM
 *
 * Nudm Context Management Service.   © 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).   All rights reserved. 
 *
 * API version: 1.3.0-alpha.6
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// This datatype contains the set of attributes obtained from type  Amf3GppAccessRegistration by deleting attributes that are not subject to modification by HTTP PATCH method. 
type Amf3GppAccessRegistrationModification struct {
	Guami *Guami `json:"guami"`
	PurgeFlag bool `json:"purgeFlag,omitempty"`
	Pei string `json:"pei,omitempty"`
	ImsVoPs *ImsVoPs `json:"imsVoPs,omitempty"`
	BackupAmfInfo []BackupAmfInfo `json:"backupAmfInfo,omitempty"`
	EpsInterworkingInfo *EpsInterworkingInfo `json:"epsInterworkingInfo,omitempty"`
	UeSrvccCapability bool `json:"ueSrvccCapability,omitempty"`
	UeMINTCapability bool `json:"ueMINTCapability,omitempty"`
}
